#include<stdio.h>
#include<stdlib.h>
#include<errno.h>
#include<fcntl.h>
#include<string.h>
#include<unistd.h>
#include<sys/ioctl.h>
#include<sys/types.h>
#include<sys/stat.h>
#include<sys/select.h>
#include<sys/time.h>

int main()
{
	int fp;
	int value;
	
	fp = open("/dev/randomNum", O_RDONLY); // open only read device
	if (fp < 0)	
	{
        	printf("Open character device file unsuccessfully!");
        	return -1;
    	}
	else
	{
		printf("- Open character device file successfully!\n");
		read(fp, &value, sizeof(value));
	    	printf("- Random number generated by character device is : %d", value);
	}
	close(fp);
	printf("\n- Close character device file successfully!\n");
}
